# Generated by Django 4.0.6 on 2022-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('shoes', 'shoes'), ('Accessories', 'accessories'), ('bags', 'bags'), ('clothes', 'clothes')], default='clothes', max_length=20),
        ),
    ]
