# Generated by Django 4.0.6 on 2022-08-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_product_availability_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('shoes', 'shoes'), ('bags', 'bags'), ('Accessories', 'accessories'), ('clothes', 'clothes')], default='clothes', max_length=20),
        ),
    ]
